### ISSUE TITLE
xSQLServerAlwaysOnAvailabilityGroupReplica - Unexpected result when trying to verify existance of Availability Group replica

### ISSUE THREAD

**Issue by joshan1120** [johlju/xSqlServerAlwaysOn#11]
I am trying to use your secondary replica resource over the one in the XSqlServer project as it offers more parameters and would make life easier. I need my DR node to have different params than my HA node and the other module doesn't seem to offer that. (Failover / readonly/ etc)

It is getting a strange error I am struggling to figure out and wonder if you have any ideas.

**PowerShell DSC resource xSQLServerAlwaysOnAvailabilityGroupReplica  failed to execute Test-TargetResource functionality with error message: Unexpected result when trying to verify existance of Availability Group replica TestSecondary\Test. Error: 
TESTPRIMARY\Test is not the primary replica. Seems that TESTPRIMARY\test is the primary replica.** 

Not sure why it is saying the same server and instance are and are not the primary.

I have stripped out most everything from my foreach and variables and am just running this code

**xSQLServerAlwaysOnAvailabilityGroupReplica addSecondariesToAoGroup
			{
				Ensure = "Present"
				AvailabilityGroup = 'MS-WE-INF-AO-AG'
				NodeName = "TestSecondary"
				AvailabilityMode = 'SynchronousCommit'
				FailoverMode = 'Automatic'
				PrimaryReplicaInstanceName = "Test"
                                InstanceName = "Test"
				PrimaryReplicaNodeName = $env:COMPUTERNAME
				PsDscRunAsCredential = $LocalAdminCreds
				DependsOn = "[xSQLServerAvailabilityGroupListener]addListener"
			}**

I guess I will open another request in the other forum also, in case you do not support this any longer.

Here is more of the stack trace also

VERBOSE: [TESTPRIMARY]: LCM:  [ Start  Test     ]  [[xSQLServerAlwaysOnAvailabilityGroupReplica]addSecondariesToAoGroup]
VERBOSE: [TESTPRIMARY]:                            [[xSQLServerAlwaysOnAvailabilityGroupReplica]addSecondariesToAoGroup] Testing state of Availability Group replica TestSecondary\Test
VERBOSE: [TESTPRIMARY]:                            [[xSQLServerAlwaysOnAvailabilityGroupReplica]addSecondariesToAoGroup] Getting state of availability group replica TestSecondary\Test
VERBOSE: [TESTPRIMARY]:                            [[xSQLServerAlwaysOnAvailabilityGroupReplica]addSecondariesToAoGroup] Waiting for Primary Replica TESTPRIMARY\Test and availability group MS-WE-INF-AO-AG to go online. Timeout will occur in 300 sec
onds.
VERBOSE: [TESTPRIMARY]:                            [[xSQLServerAlwaysOnAvailabilityGroupReplica]addSecondariesToAoGroup] Primary Replica is online.
VERBOSE: [TESTPRIMARY]: LCM:  [ End    Test     ]  [[xSQLServerAlwaysOnAvailabilityGroupReplica]addSecondariesToAoGroup]  in 3.9530 seconds.
PowerShell DSC resource xSQLServerAlwaysOnAvailabilityGroupReplica  failed to execute Test-TargetResource functionality with error message: Unexpected result when trying to verify existance of Availability Group replica TestSecondary\Test. Error: 
TESTPRIMARY\Test is not the primary replica. Seems that TESTPRIMARY\test is the primary replica. 
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost
 
VERBOSE: [TESTPRIMARY]: LCM:  [ End    Set      ]

**Comment by joshan1120** [comment]
closing got one in other project to work.

**Comment by johlju** [comment]
Yes, this resource is the base of what randomnote sent into xSQLServer. He made it shiny new and much improved :)
Happy you got it working :)
